using System;
using System.Collections.Generic;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using StardewValley;
using StardewValley.Menus;

namespace SDVRadiance
{
    /// <summary>
    /// On-screen tuner overlay, TAB-RAIL layout: a column of category tabs on the left,
    /// the selected category's controls on the right. Only one category is on screen at a
    /// time, so the panel stays short no matter how many settings exist. Occupies the right
    /// side so the world stays visible and updates live as you drag. Localized; opened with
    /// the tuner hotkey.
    /// </summary>
    internal sealed class RadianceTunerMenu : IClickableMenu
    {
        // Base (smallest) layout. Everything below scales up from here so the panel keeps its
        // share of a big window instead of shrinking into a corner of it - and so a long Thai
        // tab label has room to sit at full size rather than being squeezed to fit.
        // Wide enough for a full-length label NEXT TO an icon. At the old width the icon ate
        // the room the text needed, and the shrink-to-fit quietly dropped the longest label to
        // half the size of its neighbours rather than overflowing - legible in the code,
        // obviously wrong on screen.
        private const int BaseRailWidth = 196;
        private const int BaseContentWidth = 430;
        private const int PanelWidth = BaseRailWidth + BaseContentWidth;
        private const int BaseHeaderH = 52;
        private const int BaseFooterH = 40;

        private int RailWidth = BaseRailWidth;
        private int ContentWidth = BaseContentWidth;
        private int HeaderH = BaseHeaderH;
        private int FooterH = BaseFooterH;
        /// <summary>1 at the base size, up to 1.6 on a large window. Multiplies every row
        /// height, box and text size so the whole panel grows together.</summary>
        private float _ui = 1f;
        private int S(int v) => (int)Math.Round(v * _ui);
        private const int BodyPad = 12;   // breathing room at the top/bottom of the scrolling content
        private const int NaturalTabPitch = 54;   // rail button spacing when there is room for it
        private const int MinTabPitch = 36;       // squeezed spacing that still reads (see Reflow)
        private static readonly Rectangle DeleteSource = new(192, 256, 64, 64); // red X in mouseCursors
        private static readonly RasterizerState _scissorRaster = new() { ScissorTestEnable = true, CullMode = CullMode.None };

        private readonly ModConfig _config;
        private readonly Func<string, string> _translate;
        private readonly Action _onChange;
        private readonly Action _onSave;

        private readonly List<TunerSlider> _sliders = new();
        private readonly List<TunerToggle> _toggles = new();
        private readonly List<TunerTextButton> _buttons = new();   // content-area buttons (scroll with content)
        private readonly List<TunerChip> _chips = new();
        private readonly List<(string text, int y)> _sectionTitles = new();
        /// <summary>Read-only lines. Supplied per draw rather than baked at layout time, so a
        /// running measurement can count up without rebuilding the menu underneath it.</summary>
        private readonly List<(Func<string> text, int y)> _infoLines = new();
        private int _seenBenchStamp = -1;

        /// <summary>Tab icons: one 16x16 cell per tab, in tab order (assets/tuner-icons.png,
        /// generated by tools/make-tuner-icons.py). Loaded once and kept - a menu that
        /// reopens constantly must not re-read a file each time.</summary>
        private static Texture2D? _icons;
        private static bool _iconsTried;
        private const int IconSize = 16;
        private float _iconScale;
        private readonly List<(TunerTextButton btn, int idx)> _tabRailButtons = new();  // fixed, never scroll
        private TunerSlider? _dragging;

        // Tabs: (label key, one-line description key, content builder). Remembered across reopens.
        private readonly (string key, string desc, Action build)[] _tabDefinitions;
        private static int _lastTab;
        private int _activeTab;

        private int _scroll, _maxScroll, _bodyTop, _bodyBottom, _hintY, _contentX;
        // content-column layout cursor (build helpers advance it)
        private int _contentCursorX, _contentCursorY, _contentColumnWidth;

        public RadianceTunerMenu(ModConfig config, Func<string, string> translate, Action onChange, Action onSave)
            : base(0, 0, PanelWidth, 0, showUpperRightCloseButton: true)
        {
            _config = config;
            _translate = translate;
            _onChange = onChange;
            _onSave = onSave;
            _tabDefinitions = new (string, string, Action)[]
            {
                // Ordered the way a game's video settings are: the two global answers first
                // ("make it look right", "make it run"), then the detail grouped by family -
                // camera/film, then light, then the world - and the troubleshooting switch
                // last. The old order was the order the effects happened to be built in, which
                // left the quality control that everyone needs sitting eleventh.
                ("tuner.tab.looks",       "tuner.desc.looks",      BuildLooks),
                ("config.section.perf",   "tuner.desc.perf",       BuildPerformance),
                ("tuner.section.colorgrade", "tuner.desc.colorgrade", BuildColorGrade),
                ("tuner.section.bloom",   "tuner.desc.bloom",      BuildBloom),
                ("tuner.tab.lens",        "tuner.desc.lens",       BuildLens),
                ("tuner.section.lighting", "tuner.desc.lighting",  BuildLighting),
                ("tuner.section.shadows", "tuner.desc.shadows",    BuildShadows),
                ("tuner.section.godrays", "tuner.desc.godrays",    BuildGodRays),
                ("tuner.section.water",   "tuner.desc.water",      BuildWater),
                ("tuner.section.cloudshadow", "tuner.desc.cloudshadow", BuildCloud),
                ("tuner.tab.fog",         "tuner.desc.fog",        BuildFog),
                ("config.section.camera", "tuner.desc.camera",     BuildCamera),
                ("config.section.debug",  "tuner.desc.debug",      BuildDiagnostics),
            };
            _activeTab = Math.Clamp(_lastTab, 0, _tabDefinitions.Length - 1);
            Reflow();
        }

        private void Reopen() => Game1.activeClickableMenu = new RadianceTunerMenu(_config, _translate, _onChange, _onSave);

        // ---- content build helpers (append to lists, advance _contentCursorY) ----
        private void Section(string key) { _sectionTitles.Add((_translate(key), _contentCursorY)); _contentCursorY += S(30); }
        private void Info(Func<string> text) { _infoLines.Add((text, _contentCursorY)); _contentCursorY += S(26); }
        private void Tog(string key, Func<bool> g, Action<bool> s)
        {
            _toggles.Add(new TunerToggle(_translate(key), new Rectangle(_contentCursorX, _contentCursorY, _contentColumnWidth, S(38)), g, s) { TextScale = _ui });
            _contentCursorY += S(44);
        }
        private void Sld(string key, float min, float max, Func<float> g, Action<float> s)
        {
            _sliders.Add(new TunerSlider(_translate(key), _contentCursorX, _contentCursorY, _contentColumnWidth, min, max, g, s, S(26), S(20)) { TextScale = _ui });
            _contentCursorY += S(50);
        }
        private TunerTextButton Btn(string label, Rectangle bounds, Action onClick)
        {
            var b = new TunerTextButton(label, bounds, onClick) { TextScale = _ui };
            _buttons.Add(b);
            return b;
        }

        private void Reflow()
        {
            int vw = Game1.uiViewport.Width;
            int vh = Game1.uiViewport.Height;

            // Take a share of the window rather than a fixed number of pixels: at the base size
            // this panel is a small box on a large display, and the rail is too narrow for a
            // full-length Thai label. Height matters as much as width here, since the rail has
            // to fit twelve tabs.
            _ui = Math.Clamp(Math.Min(vw / 1600f, vh / 900f), 1f, 1.6f);
            RailWidth = S(BaseRailWidth);
            ContentWidth = S(BaseContentWidth);
            HeaderH = S(BaseHeaderH);
            FooterH = S(BaseFooterH);

            width = RailWidth + ContentWidth;
            xPositionOnScreen = vw - width - S(24);
            yPositionOnScreen = S(20);

            _sliders.Clear(); _toggles.Clear(); _buttons.Clear(); _chips.Clear(); _sectionTitles.Clear(); _tabRailButtons.Clear(); _infoLines.Clear();

            int contentTop = yPositionOnScreen + HeaderH;

            // ---- left rail: one button per tab (fixed; never scrolls) ----
            // The rail is what sets the panel height, so its pitch has to be settled FIRST.
            // At the natural pitch a long enough rail (or a short window) runs past the
            // bottom of the frame and the last tabs get drawn outside it, because the frame
            // is capped to the view while the buttons were not. Squeeze the pitch to fit
            // instead, down to a floor that still reads.
            int maxBody = (vh - S(40)) - HeaderH - FooterH;
            int tabPitch = S(NaturalTabPitch);
            if (_tabDefinitions.Length * tabPitch > maxBody)
                tabPitch = Math.Clamp(maxBody / Math.Max(1, _tabDefinitions.Length), S(MinTabPitch), S(NaturalTabPitch));

            if (!_iconsTried)
            {
                _iconsTried = true;
                _icons = RenderPipeline.Current?.LoadTexture("tuner-icons.png");
            }

            int railX = xPositionOnScreen + S(12);
            int railW = RailWidth - S(20);
            // Tie the icon to the button it sits in: when a short window squeezes the pitch,
            // a fixed icon size would poke out of the top and bottom of its own button.
            _iconScale = _icons != null ? Math.Min(2f * _ui, (tabPitch - S(10)) / (float)IconSize) : 0f;
            int iconInset = _icons != null ? (int)(IconSize * _iconScale) + S(10) : 0;
            for (int i = 0; i < _tabDefinitions.Length; i++)
            {
                int idx = i;
                var rect = new Rectangle(railX, contentTop + i * tabPitch, railW, tabPitch - S(4));
                _tabRailButtons.Add((new TunerTextButton(_translate(_tabDefinitions[i].key), rect, () =>
                {
                    _activeTab = idx; _lastTab = idx; _scroll = 0; Reflow();
                })
                { TextScale = _ui, LeftInset = iconInset }, i));
            }

            // ---- right content column: only the active tab ----
            _contentX = xPositionOnScreen + RailWidth;
            _contentCursorX = _contentX + S(16);
            _contentColumnWidth = ContentWidth - S(40);
            _contentCursorY = contentTop + BodyPad;
            // One line saying what this tab is for, before anything else on it. A column of
            // sliders assumes the reader already knows which effect they belong to.
            string descKey = _tabDefinitions[_activeTab].desc;
            Info(() => _translate(descKey));
            _contentCursorY += S(6);
            _tabDefinitions[_activeTab].build();
            int contentHeight = _contentCursorY - (contentTop + BodyPad);

            // CONSISTENT panel height across tabs: the frame is sized to the tab rail, capped
            // to the view. Switching tabs never resizes the panel; a tab whose content is
            // taller than the frame scrolls inside it (mouse wheel) instead of growing it.
            int railHeight = _tabDefinitions.Length * tabPitch;
            int bodyHeight = Math.Min(railHeight, maxBody);
            height = HeaderH + bodyHeight + FooterH;

            _bodyTop = contentTop + S(BodyPad);
            _bodyBottom = contentTop + bodyHeight - S(BodyPad);
            _hintY = yPositionOnScreen + height - S(30);
            _maxScroll = Math.Max(0, contentHeight - (_bodyBottom - _bodyTop));
            _scroll = Math.Clamp(_scroll, 0, _maxScroll);

            upperRightCloseButton.bounds.X = xPositionOnScreen + width - S(40);
            upperRightCloseButton.bounds.Y = yPositionOnScreen - S(8);
        }

        // ================= per-tab content =================

        private void BuildLooks()
        {
            // Preset buttons (4 across).
            (LookPreset preset, string key)[] presets =
            {
                (LookPreset.Off, "off"), (LookPreset.Subtle, "subtle"),
                (LookPreset.Cinematic, "cinematic"), (LookPreset.Vibrant, "vibrant")
            };
            int bw = (_contentColumnWidth - 18) / 4;
            for (int i = 0; i < presets.Length; i++)
            {
                var (preset, key) = presets[i];
                var rect = new Rectangle(_contentCursorX + i * (bw + 6), _contentCursorY, bw, 44);
                _buttons.Add(new TunerTextButton(_translate($"config.preset.{key}"), rect, () =>
                {
                    _config.ApplyPreset(preset); _onChange(); _onSave(); Reflow();
                }));
            }
            _contentCursorY += 56;

            Section("tuner.mylooks");
            int chipX = _contentCursorX;
            foreach (var prof in _config.SavedProfiles)
            {
                int cw = Math.Min(160, 44 + (int)(Game1.smallFont.MeasureString(prof.Name).X * 0.7f));
                if (chipX + cw > _contentCursorX + _contentColumnWidth - 100) { chipX = _contentCursorX; _contentCursorY += 46; }
                var rect = new Rectangle(chipX, _contentCursorY, cw, 40);
                var captured = prof;
                _chips.Add(new TunerChip
                {
                    Load = new TunerTextButton(prof.Name, rect, () => { _config.ApplyProfile(captured); _onChange(); _onSave(); Reflow(); }),
                    Delete = new Rectangle(rect.Right - 14, rect.Y - 6, 24, 24),
                    Profile = captured
                });
                chipX += cw + 12;
            }
            _buttons.Add(new TunerTextButton(_translate("tuner.save"), new Rectangle(_contentCursorX + _contentColumnWidth - 96, _contentCursorY, 96, 40), PromptSaveProfile));
            _contentCursorY += 52;

            Tog("tuner.master", () => _config.Enabled, v => _config.Enabled = v);
        }

        private void BuildColorGrade()
        {
            Tog("tuner.colorgrade", () => _config.ColorGradeEnabled, v => _config.ColorGradeEnabled = v);
            Tog("tuner.automood", () => _config.ColorGradeAuto, v => _config.ColorGradeAuto = v);
            Sld("tuner.strength", 0f, 1f, () => _config.ColorGradeStrength, v => _config.ColorGradeStrength = v);
            Sld("tuner.contrast", 0.5f, 1.5f, () => _config.ColorGradeContrast, v => _config.ColorGradeContrast = v);
            Sld("tuner.saturation", 0f, 2f, () => _config.ColorGradeSaturation, v => _config.ColorGradeSaturation = v);
            Sld("tuner.temperature", -1f, 1f, () => _config.ColorGradeTemperature, v => _config.ColorGradeTemperature = v);
            Sld("tuner.brightness", 0.5f, 1.5f, () => _config.ColorGradeBrightness, v => _config.ColorGradeBrightness = v);
            Tog("tuner.tonemap", () => _config.ColorGradeToneMap, v => _config.ColorGradeToneMap = v);
            Sld("tuner.bluelight", 0f, 1f, () => _config.BlueLightFilter, v => _config.BlueLightFilter = v);
        }

        private void BuildBloom()
        {
            Tog("tuner.bloom", () => _config.BloomEnabled, v => _config.BloomEnabled = v);
            Sld("tuner.intensity", 0f, 2f, () => _config.BloomIntensity, v => _config.BloomIntensity = v);
            Sld("tuner.bloomthreshold", 0f, 1f, () => _config.BloomThreshold, v => _config.BloomThreshold = v);
        }

        private void BuildShadows()
        {
            Tog("tuner.shadows", () => _config.DirectionalShadowsEnabled, v => _config.DirectionalShadowsEnabled = v);
            Sld("tuner.shadowstrength", 0f, 1f, () => _config.DirectionalShadowStrength, v => _config.DirectionalShadowStrength = v);
            Sld("tuner.shadowlength", 0.2f, 2f, () => _config.DirectionalShadowLength, v => _config.DirectionalShadowLength = v);
            Sld("tuner.shadowblur", 0f, 5f, () => _config.DirectionalShadowBlur, v => _config.DirectionalShadowBlur = v);
            Tog("tuner.shadowobjects", () => _config.DirectionalShadowObjects, v => _config.DirectionalShadowObjects = v);
        }

        private void BuildLighting()
        {
            Tog("tuner.lighting", () => _config.LightingEnabled, v => _config.LightingEnabled = v);
            Sld("tuner.lightindoor", 0f, 0.95f, () => _config.LightingIndoorDarkness, v => _config.LightingIndoorDarkness = v);
            Sld("tuner.lightnight", 0f, 0.95f, () => _config.LightingNightDarkness, v => _config.LightingNightDarkness = v);
            Sld("tuner.lightwarmth", 0f, 1f, () => _config.LightingWarmth, v => _config.LightingWarmth = v);
            Sld("tuner.lightboost", 0f, 2f, () => _config.LightingBoost, v => _config.LightingBoost = v);
            Sld("tuner.lightradius", 0.2f, 3f, () => _config.LightingRadiusScale, v => _config.LightingRadiusScale = v);
            Tog("tuner.lightshadows", () => _config.LightingShadows, v => _config.LightingShadows = v);
            Sld("tuner.lightshadowstrength", 0f, 1f, () => _config.LightingShadowStrength, v => _config.LightingShadowStrength = v);
            Tog("tuner.floodgi", () => _config.FloodLightingEnabled, v => _config.FloodLightingEnabled = v);
            Sld("tuner.floodstrength", 0f, 1.5f, () => _config.FloodLightingStrength, v => _config.FloodLightingStrength = v);
            Sld("tuner.floodshadow", 0f, 1f, () => _config.FloodShadowStrength, v => _config.FloodShadowStrength = v);
            Tog("tuner.windoweffects", () => _config.WindowEffectsEnabled, v => _config.WindowEffectsEnabled = v);
            Tog("tuner.windowbeam", () => _config.WindowBeamEnabled, v => _config.WindowBeamEnabled = v);
            Tog("tuner.windowroomlight", () => _config.WindowRoomLightEnabled, v => _config.WindowRoomLightEnabled = v);
        }

        private void BuildGodRays()
        {
            Tog("tuner.godrays", () => _config.GodRaysEnabled, v => _config.GodRaysEnabled = v);
            Sld("tuner.godraysintensity", 0f, 1.5f, () => _config.GodRaysIntensity, v => _config.GodRaysIntensity = v);
            Sld("tuner.godraysthreshold", 0f, 1f, () => _config.GodRaysThreshold, v => _config.GodRaysThreshold = v);
            Sld("tuner.godraysdensity", 0.1f, 1f, () => _config.GodRaysDensity, v => _config.GodRaysDensity = v);
        }

        private void BuildCloud()
        {
            Tog("tuner.cloudshadow", () => _config.CloudShadowEnabled, v => _config.CloudShadowEnabled = v);
            Tog("tuner.cloudhidevanilla", () => _config.SuppressVanillaCloudShadow, v => _config.SuppressVanillaCloudShadow = v);
            Sld("tuner.cloudcoverage", 0.1f, 0.9f, () => _config.CloudShadowCoverage, v => _config.CloudShadowCoverage = v);
            Sld("tuner.cloudcount", 0f, 1f, () => _config.CloudShadowCount, v => _config.CloudShadowCount = v);
            Sld("tuner.cloudopacity", 0f, 0.7f, () => _config.CloudShadowOpacity, v => _config.CloudShadowOpacity = v);
            Sld("tuner.cloudspeed", 0f, 0.06f, () => _config.CloudShadowSpeed, v => _config.CloudShadowSpeed = v);
        }

        private void BuildFog()
        {
            Section("tuner.section.fog");
            Tog("tuner.fog", () => _config.FogEnabled, v => _config.FogEnabled = v);
            Sld("tuner.fogcoverage", 0f, 1f, () => _config.FogCoverage, v => _config.FogCoverage = v);
            Sld("tuner.fogdensity", 0f, 1f, () => _config.FogDensity, v => _config.FogDensity = v);
            Sld("tuner.fogspeed", 0f, 0.1f, () => _config.FogSpeed, v => _config.FogSpeed = v);
            _contentCursorY += 12;
            Section("tuner.section.fognight");
            Tog("tuner.fognightmist", () => _config.FogNightMist, v => _config.FogNightMist = v);
            Sld("tuner.fognightmistcoverage", 0f, 1f, () => _config.FogNightMistCoverage, v => _config.FogNightMistCoverage = v);
            Sld("tuner.fognightmistdensity", 0f, 1f, () => _config.FogNightMistDensity, v => _config.FogNightMistDensity = v);
            Sld("tuner.fognightmistspeed", 0f, 0.1f, () => _config.FogNightMistSpeed, v => _config.FogNightMistSpeed = v);
        }

        private void BuildWater()
        {
            Tog("tuner.water", () => _config.WaterEnabled, v => _config.WaterEnabled = v);
            Sld("tuner.waterstrength", 0f, 2f, () => _config.WaterStrength, v => _config.WaterStrength = v);
            Sld("tuner.watersparkle", 0f, 1f, () => _config.WaterSparkle, v => _config.WaterSparkle = v);
            Sld("tuner.watersparkledensity", 0.2f, 2f, () => _config.WaterSparkleDensity, v => _config.WaterSparkleDensity = v);
            Sld("tuner.waterspeed", 0f, 3f, () => _config.WaterSpeed, v => _config.WaterSpeed = v);
            Tog("tuner.waterreflection", () => _config.WaterReflection, v => _config.WaterReflection = v);
            Sld("tuner.waterreflectstrength", 0f, 1f, () => _config.WaterReflectStrength, v => _config.WaterReflectStrength = v);
            Tog("tuner.waterindoors", () => _config.WaterEffectIndoors, v => _config.WaterEffectIndoors = v);

            // Per-room water switch: only in gated building interiors (not outdoors / real level water).
            GameLocation? here = Game1.currentLocation;
            if (here != null && !here.IsOutdoors && !RenderPipeline.HasLevelWater(here))
            {
                string key = here.NameOrUniqueName;
                _toggles.Add(new TunerToggle($"{_translate("tuner.waterhere")} · {here.Name}", new Rectangle(_contentCursorX, _contentCursorY, _contentColumnWidth, 38),
                    () => !_config.WaterDisabledLocations.Contains(key),
                    v =>
                    {
                        if (v) _config.WaterDisabledLocations.Remove(key);
                        else if (!_config.WaterDisabledLocations.Contains(key)) _config.WaterDisabledLocations.Add(key);
                    }));
                _contentCursorY += 44;
            }
        }

        private void BuildLens()
        {
            Section("tuner.section.tiltshift");
            Tog("tuner.tiltshift", () => _config.TiltShiftEnabled, v => _config.TiltShiftEnabled = v);
            _toggles.Add(new TunerToggle(_translate("tuner.tiltradial"), new Rectangle(_contentCursorX, _contentCursorY, _contentColumnWidth, 38),
                () => _config.TiltShiftMode == TiltShiftFocus.Radial,
                v => _config.TiltShiftMode = v ? TiltShiftFocus.Radial : TiltShiftFocus.Bands));
            _contentCursorY += 44;
            Sld("tuner.tiltradius", 0.05f, 0.9f, () => _config.TiltShiftRadius, v => _config.TiltShiftRadius = v);
            Sld("tuner.tiltfeather", 0f, 1f, () => _config.TiltShiftFeather, v => _config.TiltShiftFeather = v);
            Sld("tuner.tiltstrength", 0f, 1f, () => _config.TiltShiftStrength, v => _config.TiltShiftStrength = v);
            Sld("tuner.tilttop", 0f, 1f, () => _config.TiltShiftTopRatio, v => _config.TiltShiftTopRatio = v);
            Sld("tuner.tiltbottom", 0f, 1f, () => _config.TiltShiftBottomRatio, v => _config.TiltShiftBottomRatio = v);
            _contentCursorY += 12;
            Section("tuner.section.finishing");
            Tog("tuner.vignette", () => _config.VignetteEnabled, v => _config.VignetteEnabled = v);
            Sld("tuner.vignettestrength", 0f, 1f, () => _config.VignetteStrength, v => _config.VignetteStrength = v);
            Tog("tuner.ca", () => _config.ChromaticAberrationEnabled, v => _config.ChromaticAberrationEnabled = v);
            Sld("tuner.castrength", 0f, 1f, () => _config.ChromaticAberrationStrength, v => _config.ChromaticAberrationStrength = v);
        }

        private void BuildPerformance()
        {
            // Quality presets, kept apart from the look presets on the first tab: these change
            // what the picture costs, never what it looks like.
            Section("config.perfpreset.section");
            (PerfPreset preset, string key)[] perfPresets =
            {
                (PerfPreset.Quality, "quality"), (PerfPreset.Balanced, "balanced"), (PerfPreset.Performance, "performance")
            };
            int pw = (_contentColumnWidth - 12) / 3;
            for (int i = 0; i < perfPresets.Length; i++)
            {
                var (preset, key) = perfPresets[i];
                var rect = new Rectangle(_contentCursorX + i * (pw + 6), _contentCursorY, pw, 44);
                _buttons.Add(new TunerTextButton(_translate($"config.perfpreset.{key}"), rect, () =>
                {
                    _config.ApplyPerfPreset(preset); _onChange(); _onSave(); Reflow();
                }));
            }
            _contentCursorY += 56;

            Sld("config.renderscale.name", 0.5f, 1f, () => _config.RenderScale, v => _config.RenderScale = v);
            Sld("config.rendersharpness.name", 0f, 2f, () => _config.RenderSharpness, v => _config.RenderSharpness = v);

            // Measure this machine instead of guessing at it.
            Section("config.bench.section");
            _buttons.Add(new TunerTextButton(_translate("config.bench.run"),
                new Rectangle(_contentCursorX, _contentCursorY, Math.Min(300, _contentColumnWidth), 44), () =>
                {
                    RenderPipeline.Current?.StartBenchmark(_config);
                    Reflow();
                }));
            _contentCursorY += 54;

            if (RenderPipeline.BenchRunning)
                Info(() => $"{_translate("config.bench.running")} {RenderPipeline.BenchProgress * 100f:0}%");
            foreach (string line in RenderPipeline.BenchSummary)
            {
                string captured = line;
                Info(() => captured);
            }
            if (!RenderPipeline.BenchRunning && RenderPipeline.BenchSummary.Count > 0
                && Math.Abs(RenderPipeline.BenchSuggestedScale - _config.RenderScale) > 0.001f)
            {
                _contentCursorY += 6;
                _buttons.Add(new TunerTextButton(_translate("config.bench.apply"),
                    new Rectangle(_contentCursorX, _contentCursorY, Math.Min(300, _contentColumnWidth), 44), () =>
                    {
                        _config.RenderScale = RenderPipeline.BenchSuggestedScale;
                        _config.Clamp(); _onChange(); _onSave(); Reflow();
                    }));
                _contentCursorY += 54;
            }
        }

        private void BuildCamera()
        {
            // Was reachable from GMCM only, which meant the two menus disagreed about what
            // this mod even contains.
            _toggles.Add(new TunerToggle(_translate("config.camera.mode.smooth"),
                new Rectangle(_contentCursorX, _contentCursorY, _contentColumnWidth, S(38)),
                () => _config.CameraMode == CameraMode.Smooth,
                v => _config.CameraMode = v ? CameraMode.Smooth : CameraMode.Off)
            { TextScale = _ui });
            _contentCursorY += S(44);
            Sld("config.smoothcam.speed.name", 0.05f, 1f, () => _config.CameraFollowSpeed, v => _config.CameraFollowSpeed = v);
        }

        private void BuildDiagnostics()
        {
            Tog("config.debug.name", () => _config.DebugLogging, v => _config.DebugLogging = v);
        }

        // ================= interaction =================

        private void PromptSaveProfile()
        {
            Game1.activeClickableMenu = new TextEntryMenu(_translate("tuner.naming"), "",
                onDone: name =>
                {
                    if (!string.IsNullOrWhiteSpace(name))
                    {
                        _config.SavedProfiles.Add(_config.CaptureProfile(name.Trim()));
                        _onSave();
                    }
                    Reopen();
                },
                onCancel: Reopen);
        }

        private bool Visible(Rectangle contentRect)
        {
            int top = contentRect.Y - _scroll;
            int bottom = contentRect.Bottom - _scroll;
            return bottom > _bodyTop && top < _bodyBottom;
        }

        public override void gameWindowSizeChanged(Rectangle oldBounds, Rectangle newBounds)
        {
            base.gameWindowSizeChanged(oldBounds, newBounds);
            Reflow();
        }

        public override void receiveScrollWheelAction(int direction)
        {
            if (_maxScroll > 0)
                _scroll = Math.Clamp(_scroll - Math.Sign(direction) * 48, 0, _maxScroll);
        }

        public override void receiveLeftClick(int x, int y, bool playSound = true)
        {
            // Rail buttons are fixed (no scroll offset) and always clickable.
            foreach (var (btn, idx) in _tabRailButtons)
                if (btn.Bounds.Contains(x, y)) { if (idx != _activeTab) Game1.playSound("smallSelect"); btn.OnClick(); return; }

            if (y >= _bodyTop && y <= _bodyBottom && x >= _contentX)
            {
                foreach (var button in _buttons)
                    if (Visible(button.Bounds) && button.Bounds.Contains(x, y + _scroll)) { Game1.playSound("smallSelect"); button.OnClick(); return; }
                foreach (var c in _chips)
                {
                    if (Visible(c.Load.Bounds) && c.Delete.Contains(x, y + _scroll)) { DeleteChip(c); return; }
                    if (Visible(c.Load.Bounds) && c.Load.Bounds.Contains(x, y + _scroll)) { Game1.playSound("smallSelect"); c.Load.OnClick(); return; }
                }
                foreach (var t in _toggles)
                    if (Visible(t.Row) && t.Hit(x, y + _scroll)) { t.Set(!t.Get()); Game1.playSound("drumkit6"); _onChange(); _onSave(); return; }
                foreach (var s in _sliders)
                    if (Visible(s.Track) && s.Track.Contains(x, y + _scroll)) { _dragging = s; s.SetFromX(x); _onChange(); return; }
            }
            base.receiveLeftClick(x, y, playSound);
        }

        public override void update(GameTime time)
        {
            base.update(time);
            // A measurement finishing adds result lines and the apply button, so the layout
            // has to be rebuilt once it lands. The running counter itself needs no rebuild:
            // those lines ask for their text every draw.
            if (_seenBenchStamp != RenderPipeline.BenchStamp)
            {
                _seenBenchStamp = RenderPipeline.BenchStamp;
                Reflow();
            }
        }

        public override void receiveRightClick(int x, int y, bool playSound = true)
        {
            if (y < _bodyTop || y > _bodyBottom) return;
            foreach (var c in _chips)
                if (Visible(c.Load.Bounds) && c.Load.Bounds.Contains(x, y + _scroll)) { DeleteChip(c); return; }
        }

        private void DeleteChip(TunerChip c)
        {
            _config.SavedProfiles.Remove(c.Profile);
            _onSave(); Game1.playSound("trashcan"); Reflow();
        }

        public override void leftClickHeld(int x, int y)
        {
            if (_dragging != null) { _dragging.SetFromX(x); _onChange(); }
        }

        public override void releaseLeftClick(int x, int y)
        {
            if (_dragging != null) { _dragging = null; _onSave(); }
            base.releaseLeftClick(x, y);
        }

        protected override void cleanupBeforeExit()
        {
            _onSave();
            base.cleanupBeforeExit();
        }

        public override void draw(SpriteBatch spriteBatch)
        {
            int innerW = width - S(56);

            drawTextureBox(spriteBatch, Game1.menuTexture, new Rectangle(0, 256, 60, 60),
                xPositionOnScreen, yPositionOnScreen, width, height, Color.White, 1f, drawShadow: true);
            TunerText.DrawFit(spriteBatch, _translate("tuner.title"), new Vector2(xPositionOnScreen + S(28), yPositionOnScreen + S(22)), innerW - S(40), Game1.textColor, _ui);

            // Rail divider
            int divX = xPositionOnScreen + RailWidth;
            spriteBatch.Draw(Game1.staminaRect, new Rectangle(divX, _bodyTop - 6, 2, _bodyBottom - _bodyTop + 12), Color.Black * 0.2f);

            // Rail buttons (active highlighted)
            foreach (var (btn, idx) in _tabRailButtons)
            {
                if (idx == _activeTab)
                    spriteBatch.Draw(Game1.staminaRect, new Rectangle(btn.Bounds.X - S(4), btn.Bounds.Y - S(2), btn.Bounds.Width + S(8), btn.Bounds.Height + S(4)), new Color(196, 130, 66) * 0.55f);
                btn.Draw(spriteBatch, 0, idx == _activeTab);
                if (_icons != null && _iconScale > 0f && idx < _icons.Width / IconSize)
                {
                    // Inactive tabs sit back a little so the icon column reads as a list
                    // rather than twelve competing colours.
                    float iconScale = _iconScale;
                    spriteBatch.Draw(_icons,
                        new Vector2(btn.Bounds.X + S(8), btn.Bounds.Center.Y - IconSize * iconScale / 2f),
                        new Rectangle(idx * IconSize, 0, IconSize, IconSize),
                        idx == _activeTab ? Color.White : Color.White * 0.72f,
                        0f, Vector2.Zero, iconScale, SpriteEffects.None, 0.9f);
                }
            }

            // Clip the scrolling content to the body rect so a half-scrolled row can't draw
            // over the header/footer. Requires flushing this batch and reopening one with a
            // scissor-enabled rasterizer, then restoring a normal batch for the rest.
            var device = spriteBatch.GraphicsDevice;
            Rectangle prevScissor = device.ScissorRectangle;
            spriteBatch.End();
            spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, _scissorRaster);
            device.ScissorRectangle = Rectangle.Intersect(device.Viewport.Bounds,
                new Rectangle(_contentX, _bodyTop, ContentWidth, _bodyBottom - _bodyTop));

            int dy = -_scroll;
            foreach (var (text, cy) in _sectionTitles)
            {
                var r = new Rectangle(_contentX + S(16), cy, _contentColumnWidth, S(24));
                if (Visible(r)) TunerText.DrawFit(spriteBatch, text, new Vector2(_contentX + S(16), cy + dy), _contentColumnWidth, Game1.textColor * 0.85f, 0.85f * _ui);
            }
            foreach (var (text, cy) in _infoLines)
            {
                var r = new Rectangle(_contentX + S(16), cy, _contentColumnWidth, S(22));
                if (Visible(r)) TunerText.DrawFit(spriteBatch, text(), new Vector2(_contentX + S(16), cy + dy), _contentColumnWidth, Game1.textColor * 0.7f, 0.72f * _ui);
            }
            foreach (var btn in _buttons) if (Visible(btn.Bounds)) btn.Draw(spriteBatch, dy);
            foreach (var c in _chips)
                if (Visible(c.Load.Bounds))
                {
                    c.Load.Draw(spriteBatch, dy);
                    spriteBatch.Draw(Game1.mouseCursors, new Rectangle(c.Delete.X, c.Delete.Y + dy, c.Delete.Width, c.Delete.Height), DeleteSource, Color.White);
                }
            foreach (var t in _toggles) if (Visible(t.Row)) t.Draw(spriteBatch, dy);
            foreach (var s in _sliders) if (Visible(s.Track)) s.Draw(spriteBatch, dy);

            spriteBatch.End();
            device.ScissorRectangle = prevScissor;
            spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise);

            if (_maxScroll > 0)
            {
                int trackX = xPositionOnScreen + width - 18;
                int trackH = _bodyBottom - _bodyTop;
                spriteBatch.Draw(Game1.staminaRect, new Rectangle(trackX, _bodyTop, 6, trackH), Color.Black * 0.25f);
                int barH = Math.Max(30, (int)(trackH * (float)trackH / (trackH + _maxScroll)));
                int barY = _bodyTop + (int)((trackH - barH) * (_scroll / (float)_maxScroll));
                spriteBatch.Draw(Game1.staminaRect, new Rectangle(trackX, barY, 6, barH), new Color(196, 130, 66));
            }

            TunerText.DrawFit(spriteBatch, _translate("tuner.hint"), new Vector2(xPositionOnScreen + 28, _hintY), innerW, Game1.textColor * 0.7f, 0.8f);

            base.draw(spriteBatch);
            drawMouse(spriteBatch);
        }

    }
}
